spring:
  datasource:
    # RDS 접근 설정
    url: ${RDS_END_POINT}
    username: ${RDS_MYSQL_ADMIN_ID}
    password: ${RDS_MYSQL_ADMIN_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true
    defer-datasource-initialization: true